/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ProtonButton {
        "color": string;
        "href": string | any;
        "radius": 'sm'|'md'|'lg'|'none';
    }
    interface ProtonNavbar {
        "fixed": boolean;
        "spacing": 'between'|'around'|'evenly';
    }
    interface ProtonNavlink {
        "href": string;
    }
    interface ProtonNavlinkHolder {
    }
    interface ProtonSlide {
    }
    interface ProtonSlideshow {
        "showArrow": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLProtonButtonElement extends Components.ProtonButton, HTMLStencilElement {
    }
    var HTMLProtonButtonElement: {
        prototype: HTMLProtonButtonElement;
        new (): HTMLProtonButtonElement;
    };
    interface HTMLProtonNavbarElement extends Components.ProtonNavbar, HTMLStencilElement {
    }
    var HTMLProtonNavbarElement: {
        prototype: HTMLProtonNavbarElement;
        new (): HTMLProtonNavbarElement;
    };
    interface HTMLProtonNavlinkElement extends Components.ProtonNavlink, HTMLStencilElement {
    }
    var HTMLProtonNavlinkElement: {
        prototype: HTMLProtonNavlinkElement;
        new (): HTMLProtonNavlinkElement;
    };
    interface HTMLProtonNavlinkHolderElement extends Components.ProtonNavlinkHolder, HTMLStencilElement {
    }
    var HTMLProtonNavlinkHolderElement: {
        prototype: HTMLProtonNavlinkHolderElement;
        new (): HTMLProtonNavlinkHolderElement;
    };
    interface HTMLProtonSlideElement extends Components.ProtonSlide, HTMLStencilElement {
    }
    var HTMLProtonSlideElement: {
        prototype: HTMLProtonSlideElement;
        new (): HTMLProtonSlideElement;
    };
    interface HTMLProtonSlideshowElement extends Components.ProtonSlideshow, HTMLStencilElement {
    }
    var HTMLProtonSlideshowElement: {
        prototype: HTMLProtonSlideshowElement;
        new (): HTMLProtonSlideshowElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "proton-button": HTMLProtonButtonElement;
        "proton-navbar": HTMLProtonNavbarElement;
        "proton-navlink": HTMLProtonNavlinkElement;
        "proton-navlink-holder": HTMLProtonNavlinkHolderElement;
        "proton-slide": HTMLProtonSlideElement;
        "proton-slideshow": HTMLProtonSlideshowElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ProtonButton {
        "color"?: string;
        "href"?: string | any;
        "onClicked"?: (event: CustomEvent<any>) => void;
        "radius"?: 'sm'|'md'|'lg'|'none';
    }
    interface ProtonNavbar {
        "fixed"?: boolean;
        "spacing"?: 'between'|'around'|'evenly';
    }
    interface ProtonNavlink {
        "href"?: string;
    }
    interface ProtonNavlinkHolder {
    }
    interface ProtonSlide {
    }
    interface ProtonSlideshow {
        "showArrow"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "proton-button": ProtonButton;
        "proton-navbar": ProtonNavbar;
        "proton-navlink": ProtonNavlink;
        "proton-navlink-holder": ProtonNavlinkHolder;
        "proton-slide": ProtonSlide;
        "proton-slideshow": ProtonSlideshow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "proton-button": LocalJSX.ProtonButton & JSXBase.HTMLAttributes<HTMLProtonButtonElement>;
            "proton-navbar": LocalJSX.ProtonNavbar & JSXBase.HTMLAttributes<HTMLProtonNavbarElement>;
            "proton-navlink": LocalJSX.ProtonNavlink & JSXBase.HTMLAttributes<HTMLProtonNavlinkElement>;
            "proton-navlink-holder": LocalJSX.ProtonNavlinkHolder & JSXBase.HTMLAttributes<HTMLProtonNavlinkHolderElement>;
            "proton-slide": LocalJSX.ProtonSlide & JSXBase.HTMLAttributes<HTMLProtonSlideElement>;
            "proton-slideshow": LocalJSX.ProtonSlideshow & JSXBase.HTMLAttributes<HTMLProtonSlideshowElement>;
        }
    }
}
